export { default as CartIcon } from './CartIcon'
export { default as UserIcon } from './UserIcon'
export { default as LogoutIcon } from './Logout'
export { default as MenuIcon } from './Menu'
export { default as CloseIcon } from './CloseIcon'
export { default as GoogleIcon } from './GoogleIcon'
export { default as SpanishIcon } from './SpanishIcon'
export { default as EnglishIcon } from './EnglishIcon'
export { default as ChevronIcon } from './ChevronIcon'

export { default as OrdersIcon } from './OrdersIcon'
export { default as ProductsIcon } from './ProductsIcon'
export { default as SettingsIcon } from './SettingsIcon'
export { default as Spinner } from './Spinner'
export { default as AddIcon } from './AddIcon'
export { default as RemoveIcon } from './RemoveIcon'
